#!/bin/bash
appDir=$(dirname "$0")'/launcher.sh'
#Opens Terminal and brings the focus on its window
osascript -e 'do shell script "open -a Terminal \"'"$appDir"'\"" 
tell application "Terminal"
    set index of window 2 to 1
end tell
tell application "System Events" to tell process "Terminal"
    perform action "AXRaise" of window 1
end tell'